### ISSUE TITLE
won't build with Linux 4.4 -- multiple problems

### ISSUE THREAD

**Issue by moses-moore-spafax** [Braklet/rtl8811AU_rtl8821A-linux#1]
Can't compile. `make` errors out with many screens of errors like this:

```
  /root/rtl8811AU_rtl8821A-linux/include/rtw_debug.h:187:19: 
    error: void value not ignored as it ought to be  
  #define _seqdump seq_printf
```

[build.log.txt](https://github.com/Braklet/rtl8811AU_rtl8821A-linux/files/671880/build.log.txt)

**Comment by moses-moore-spafax** [comment]
Tried building again after commenting out `#define _seqdump` because it seems to be a no-op in rtw_debug.h, I get these warnings-as-errors:

```/root/rtl8811AU_rtl8821A-linux/core/rtw_debug.c: In function ‘dump_drv_version’:
/root/rtl8811AU_rtl8821A-linux/core/rtw_debug.c:65:2: error: implicit declaration of function ‘DBG_871X_SEL_NL’ [-Werror=implicit-function-declaration]
  DBG_871X_SEL_NL(sel, "%s %s\n", DRV_NAME, DRIVERVERSION);
  ^
/root/rtl8811AU_rtl8821A-linux/core/rtw_debug.c:66:46: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
  DBG_871X_SEL_NL(sel, "build time: %s %s\n", __DATE__, __TIME__);
                                              ^
/root/rtl8811AU_rtl8821A-linux/core/rtw_debug.c:66:56: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  DBG_871X_SEL_NL(sel, "build time: %s %s\n", __DATE__, __TIME__);
                                                        ^
/root/rtl8811AU_rtl8821A-linux/core/rtw_debug.c: In function ‘mac_reg_dump’:
/root/rtl8811AU_rtl8821A-linux/core/rtw_debug.c:104:3: error: implicit declaration of function ‘DBG_871X_SEL’ [-Werror=implicit-function-declaration]
   DBG_871X_SEL(sel, " 0x%08x ", rtw_read32(adapter,i));
   ^
cc1: some warnings being treated as errors
```

So I added `EXTRA_CFLAGS += -w` to the Makefile -- which I know is a Bad Idea™ -- and tried to compile again but it stopped with more errors:

```/root/rtl8811AU_rtl8821A-linux/os_dep/linux/usb_intf.c: In function ‘rtw_drv_entry’:
/root/rtl8811AU_rtl8821A-linux/os_dep/linux/usb_intf.c:1887:19: error: ‘RTW_DBGDUMP’ undeclared (first use in this function)
  dump_drv_version(RTW_DBGDUMP);
                   ^
/root/rtl8811AU_rtl8821A-linux/os_dep/linux/usb_intf.c:1887:19: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:258: recipe for target '/root/rtl8811AU_rtl8821A-linux/os_dep/linux/usb_intf.o' failed
```

**Comment by moses-moore-spafax** [comment]
went back to rtw_debug.h, uncommented the `#define` and commented out the two no-op places where it is (not) used instead.  Tried to rebuild, got a new error, and here's where I don't have any more time to investigate.

```/root/rtl8811AU_rtl8821A-linux/hal/hal_com_phycfg.c:2578:6: error: ‘file_path’ redeclared as different kind of symbol
 char file_path[PATH_LENGTH_MAX];
      ^
In file included from include/linux/compat.h:15:0,
                 from include/linux/ethtool.h:16,
                 from include/linux/netdevice.h:42,
                 from /root/rtl8811AU_rtl8821A-linux/include/osdep_service_linux.h:35,
                 from /root/rtl8811AU_rtl8821A-linux/include/osdep_service.h:41,
                 from /root/rtl8811AU_rtl8821A-linux/include/drv_types.h:32,
                 from /root/rtl8811AU_rtl8821A-linux/hal/hal_com_phycfg.c:22:
include/linux/fs.h:2598:14: note: previous declaration of ‘file_path’ was here
 extern char *file_path(struct file *, char *, int);
              ^
scripts/Makefile.build:258: recipe for target '/root/rtl8811AU_rtl8821A-linux/hal/hal_com_phycfg.o' failed
```

**Comment by Braklet** [comment]
I haven't had to use this driver since upgrading the original hosts to Ubuntu 14.04.  I am now using my Edimax AC600 USB dongle in a first generation Raspberry Pi 1 model B+ running OSMC and have had zero problems with the driver embedded in OSMC.  So I'm afraid I will not update this driver for new kernels.
